### ISSUE TITLE
Issue with ktf.console

### ISSUE THREAD

**Issue by leonardosoavi** [PowerScript/KatanaFramework#15]
Hi RedToor, 
I installed katana following those instructions:
git clone https://github.com/PowerScript/KatanaFramework.git
cd KatanaFramework
sudo sh dependencies
sudo python install
and all went fine, but when i tried to start the program with ktf.console  it says:
Traceback (most recent call last):
  File "ktf.console", line 9, in <module>
    from core.MainListLibrary import *
  File "/usr/share/KatanaFramework/core/MainListLibrary.py", line 10, in <module>
    from Internal import (
  File "/usr/share/KatanaFramework/core/Internal.py", line 21, in <module>
    import fcntl        ,struct   ,readline,rlcompleter,subprocess ,os
ImportError: No module named readline

is it me or there is a problem with the file?

**Comment by RedToor** [comment]
Hi @leonardosoavi, what distribution you use? you will can install the library _pip install readline_ or _easy_install readline_.

**Comment by WasiArain** [comment]
still not working!

**Comment by sumitsinghbaneshi** [comment]
`I am impacted with the same issue.`

`After doing pip install readline same issue.`
