### ISSUE TITLE
SSL: Unknown Protocol error(ssl: c590)

### ISSUE THREAD

**Issue by Artook10** [PowerScript/KatanaFramework#31]
Running Linux Mint 18 and recently downloaded Katana. Receive this error when I enter url target. SSL: Unknown Protocol: unknown protocol ( ssl:c590) Anyone see this before?

**Comment by Artook10** [comment]
I was able to correct this issue on my own. Just had to change SSL permission DUH.

**Comment by Kolovos21** [comment]
Hello! How do you change the SSL Permission??

**Comment by Kolovos21** [comment]
> I was able to correct this issue on my own. Just had to change SSL permission DUH.

Hello!How you SSL permission
