### ISSUE TITLE
Syntax Error on Fedora 31

### ISSUE THREAD

**Issue by DoctorPaint** [PowerScript/KatanaFramework#37]
Hi guys,
trying to install KatanaFramework on Fedora 31 but I get back this message on my terminal

Python install
  File "install", line 24
    print ""
           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("")?

Any clue why?
Any suggest how can I fix it?

**Comment by L1siwo** [comment]
python2 install , should be fine
