### ISSUE TITLE
get GPS Location with anf/af.imagen module

### ISSUE THREAD

**Issue by cacaocaca** [PowerScript/KatanaFramework#4]
I would like ask one information for example if i use anf/af.imagen and on extract_all show me it 
|ExifTool Version Number         : 10.02
 |File Name                       : IMG-20160722-WA0006.jpg
 |Directory                       : /root/Scrivania/b
 |File Size                       : 166 kB
 |File Modification Date/Time     : 2016:07:22 20:44:58+02:00
 |File Access Date/Time           : 2016:07:23 02:21:14+02:00
 |File Inode Change Date/Time     : 2016:07:23 02:19:08+02:00
 |File Permissions                : rwxrwx---
 |File Type                       : JPEG
 |File Type Extension             : jpg
 |MIME Type                       : image/jpeg
 |JFIF Version                    : 1.01
 |Resolution Unit                 : None
 |X Resolution                    : 72
 |Y Resolution                    : 72
 |Exif Byte Order                 : Big-endian (Motorola, MM)
 |Orientation                     : Horizontal (normal)
 |Color Space                     : sRGB
 |Exif Image Width                : 1600
 |Exif Image Height               : 1200
 |Current IPTC Digest             : d41d8cd98f00b204e9800998ecf8427e
 |IPTC Digest                     : d41d8cd98f00b204e9800998ecf8427e
 |Image Width                     : 1600
 |Image Height                    : 1200
 |Encoding Process                : Baseline DCT, Huffman coding
 |Bits Per Sample                 : 8
 |Color Components                : 3
 |Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
 |Image Size                      : 1600x1200
 |Megapixels                      : 1.9
How can i detect or found the gps location ? Is there a simple way for track the location ?

**Comment by RedToor** [comment]
if not show GPT information is because the photo not have it.

**Comment by cacaocaca** [comment]
Yes but what do you mean ?Do you want to say  while make one photo the kind of phone  don't save gps location  or gps no was enable at that moment ?

**Comment by RedToor** [comment]
You have enable GPS location in your phone when take the photo. see this [Link](http://www.phonearena.com/news/How-to-enable-or-disable-photo-and-video-geo-location-on-Android_id62637)

**Comment by cacaocaca** [comment]
Thanks bro bit but i have read on internet the new iphone the gps are automatic enable while take one pic right ? But i don t know if is same for android .. And another thing facebook or orther social  eliminate information about pic when upload for privacy is right ?

**Comment by RedToor** [comment]
yes, on social networks is normal delete metadata automatically, if you take directly of store phone might have the metadata.

**Comment by cacaocaca** [comment]
Thanks for information and good work :)

**Comment by RedToor** [comment]
Thanks, I'll close this "issue", if u have any question open a new issue.

**Comment by cacaocaca** [comment]
Is possible skype don't delete information when upload image becouse i did a test and work so i ask another thing about another pic and  i don t know if i send pic with gmail he delete information or if i zip the pics gmail can t delete information about jpg but i think the best thing is connect the movil with usb and pass pic direct on pc or no?

**Comment by RedToor** [comment]
yes, pass pic direct. not will delete information.
