### ISSUE TITLE
The framework doesn't updates

### ISSUE THREAD

**Issue by condor666** [PowerScript/KatanaFramework#6]
Hi,
I'm using Arch Linux and before using it i needed to install a few dependencies : 
`yaourt -Ss scapy      
yaourt -S python2-libusb1 python-libusb1
yaourt -S python-pexpect python2-pexpect
yaourt -S mysql-python`
I didn't installed it from git, i've added the blackarch repo so i could installed it with pacman or yaourt :
`yaourt -S katana`
To update normally i should use this :
`[condor666@arch]: ~>$ sudo katana-ktfupdate 
[sudo] Mot de passe de condor666 : 

     [!] Update - Katana framework
     [!] Version Current : Core:0.0.0.8 Build:0055 Date 22/01/2016 - 03/03/2016
     [!] Last Version    : Core:0.0.1.0 Build:0065 Date 08/10/16
     [!] Downloading Last Version
     [!] Upgrading.
     [+] Katana framework was Updated.

[condor666@arch]: ~>$ 
`
When i relaunch the command i've exactly the same command, i tried another way :
I launch the framework :
`[condor666@arch]: ~>$ sudo katana-ktfconsole`
After that i type "u"
And i see this :
`  /\ \              /\ \__                             
    \ \ \/'\      __  \ \ ,_\    __      ___      __     
     \ \ , <    /'__`\ \ \ \/  /'__`\  /' _ `\  /'__`\   
      \ \  \`\ /\ \L\.\_\ \ \_/\ \L\.\_/\ \/\ \/\ \L\.\_ 
       \ \_\ \_\ \__/.\_\ \__\ \__/.\_\ \_\ \_\ \__/.\_
        \/_/\/_/\/__/\/_/ \/__/\/__/\/_/\/_/\/_/\/__/\/_/

         .-.--.  
         \  \==\ 
         /- /==/  Katana Framework                    
        /' /==/   Core     = 0.0.0.8, Build: 0055
        |,|==|    Date     = 22/01/2016 - 03/03/2016
        \  \==\   Theme    = Warrior theme
         \ ,\==\  Modules  = 31 Scritp's
         / -/==/  By RedToor
         `-'--'  
          
 KTF>u

     [!] Update - Katana framework
     [!] Version Current : Core:0.0.0.8 Build:0055 Date 22/01/2016 - 03/03/2016
     [!] Last Version    : Core:0.0.1.0 Build:0065 Date 08/10/16
     [!] Downloading Last Version
     [!] Upgrading.
     [+] Katana framework was Updated.

[condor666@arch]: ~>$ 
`
But it seems nothing is updated

**Comment by RedToor** [comment]
Hi @condor666 u have a very old version of katana, use `sudo ktf.console`

**Comment by condor666** [comment]
It doesn't works, i'll remove the repo version and install the git version, normally it should work after that.

**Comment by condor666** [comment]
Ok, everything went fine, but i can't launch it normally cause with arch linux the default python is python 3, so i must launch it with `sudo python2 ktf.console`
You should use `#!/usr/bin/env python2`

**Comment by RedToor** [comment]
thanks so much for use katana, i'll add your suggestion. ;)

**Comment by condor666** [comment]
And in the beginning you could add Arch Linux as supported OS ;)

**Comment by RedToor** [comment]
Yes, thanks for your contribution. :)

**Comment by RedToor** [comment]
Allrigh!!! u can give me the version distro pleasE?

**Comment by condor666** [comment]
There's not really a version because it's rolling update but i give you the OS name with the kernel version :
`Linux arch 4.8.6-1-ARCH`

**Comment by RedToor** [comment]
No problem, added !!! thanks
