### ISSUE TITLE
BUG: Call to 'kilall' instead of 'killall' in evil_twin.py

### ISSUE THREAD

**Issue by ThomasTJdev** [PowerScript/KatanaFramework#7]
Hi RedToor

**Regarding module: ewil_twin.py**
KatanaFramework/modules/wifi/evil_twin.py
Line 59

Current call:
`commands.getoutput("kilall "+p)`

Instead of (2 x l):
`commands.getoutput("killall "+p)`

Kind regards
TTJ

**Comment by RedToor** [comment]
fixed !
