### ISSUE TITLE
ENHANCEMENT: Invoke module from dashboard

### ISSUE THREAD

**Issue by ThomasTJdev** [PowerScript/KatanaFramework#8]
Hi RedToor,

At the moment I need to `use cat/module`, and then I need to call the invoke command but specifying the recently opened modules name again `invoke cat/module`. Would it be possible to:

1. Invoke modules from the dashboard (console frontpage)
2. And invoke modules with only the command invoke when using the module (console use xx)

**Current scenario:**
```
 [ktf]:use set/facebrok
  ↳[ktf](set/facebrok):invoke set/facebrok
```

**Enhancement 1:**
```
 [ktf]:invoke set/facebrok
```

**Enhancement 2:**
```
 [ktf]:use set/facebrok
  ↳[ktf](set/facebrok):invoke
```

Kind regards

**Comment by ThomasTJdev** [comment]
And just a sidenote for other users who is having python3 as primarily on their system. You'll get in trouble while calling ktf.run without specifying python2:

**Current scenario:**
```
def Invoke(module):
	subprocess.Popen(["xterm","-T","Invoke["+module[len(INVOKE)+1:]+"]","-e","ktf.run","-m",module[len(INVOKE)+1:],"-q"])
```
**With python3 as primarily:**
```
def Invoke(module):
	subprocess.Popen(["xterm","-T","Invoke["+module[len(INVOKE)+1:]+"]","-e","python2","ktf.run","-m",module[len(INVOKE)+1:],"-q"])
```

**Comment by RedToor** [comment]
Fixed!!! Thanks so much @ThomasTJdev
